package docs_test

import (
	"os"
	"strings"
	"testing"
)

func TestGUIParityEvidenceMentionsKeyRegressionTests(t *testing.T) {
	b, err := os.ReadFile("gui-parity-evidence.md")
	if err != nil {
		t.Fatal(err)
	}
	s := string(b)
	for _, want := range []string{
		"docs/gui-accessibility-keyboard-audit.md",
		"TestGUIAccessibilityKeyboardAuditMapsParityEvidence",
		"docs/gui-mutating-pages-evidence.md",
		"TestConfigMultiSelectRouteProviders",
		"TestSkillsInstallRunsInBackgroundWithBusyMarker",
		"TestMemoryDeleteWithConfirm",
		"TestPluginsPageCanNavigateCatalogAndInstall",
		"TestPluginsPageSurfacesScanResultsAndRollback",
		"TestProvidersAddCustomProviderUpdatesCatalog",
		"TestAppCodeDerivedFeatureInventoryHasJourneyEvidence",
		"TestTUICodeDerivedFeatureInventoryHasJourneyEvidence",
		"docs/artifacts/gui/native/manifest.json",
		"TestGUINativeVisualArtifactBundle",
		"TestAppObjectiveUIQualityMetrics",
		"TestTUIObjectiveUIQualityMetrics",
		"TestServeRejectsNonLocalBind",
		"TestHandlerStaticAndAPIContracts",
		"TestServiceValidationErrors",
		"TestStreamJSONLinesStopsOnContextOrClosedEvents",
		"TestAppPremiumShellVisualContract",
		"TestAppHomeGoldenSnapshotTokens",
		"TestAppEveryPageGoldenSnapshotTokens",
		"TestAppPaletteGoldenSnapshotTokens",
		"TestAppLiveSessionsPluginsGoldenSnapshotTokens",
		"TestAppEveryPageKeyboardJourney",
		"TestAppEveryPageQuickJumpJourney",
		"TestAppHomePageResumeFeatureJourney",
		"TestAppLivePageFeatureJourney",
		"TestAppSessionsPageFeatureJourney",
		"TestAppProjectsPageFeatureJourney",
		"TestAppMachinesPageFeatureJourney",
		"TestAppConfigMemorySkillsFeatureJourneys",
		"TestAppProvidersModelsCronsFeatureJourneys",
		"TestAppPluginsPageFeatureJourney",
		"TestAppViewPaintsFullCanvas",
		"TestAppRenderSoakPaintsAndDoesNotLeakGoroutines",
		"TestAppKeyboardE2ENavigatePaletteAndOpen",
		"TestScanGitHubCanceledSkipsCommands",
		"TestScanSuggestCanceledSkipsModel",
		"TestNotepadTabSwitchFlushesDirtyNotes",
		"TestNotepadQuitFlushesDirtyNotes",
		"TestGitLinesUsesCachedSummary",
		"TestGitSummaryRefreshesOnUpdateEventsOnly",
		"TestRenderSoakDoesNotSpawnWorkOrLeakGoroutines",
		"TestTUILiveLoopResourceMeasurement",
		"TestTUIPlanPanelFeatureJourney",
		"TestTUILeftRailFeatureJourney",
		"TestTUIChangesPanelFeatureJourney",
		"TestTUIGitPanelFeatureJourney",
		"TestTUITerminalPanelFeatureJourney",
		"TestTUINotepadPanelFeatureJourney",
		"TestTUIEveryRightPanelTabKeyboardJourney",
		"TestTUITasksPanelFeatureJourney",
		"TestTUIShellsPanelFeatureJourney",
		"TestTUIRightPanelCycleKeyboardJourney",
		"TestMentionFileIndexCachesBetweenKeystrokes",
		"TestTUIKeyboardE2EHomeAndBackgroundActions",
		"TestTUIComposerTranscriptJourney",
		"TestTUIEmptyComposerGoldenSnapshotTokens",
		"TestTUIComposerMentionMenuGoldenSnapshotTokens",
		"TestTUIComposerTranscriptGoldenSnapshotTokens",
		"TestTUIRightPanelGitGoldenSnapshotTokens",
		"TestTUIEveryRightPanelTabGoldenSnapshotTokens",
		"TestTUIRightPanelPremiumSurfaceGoldenSnapshotTokens",
		"TestTUISlashCommandJourneyFromComposer",
		"TestPremiumInteractionViewSoak",
		"TestTUIToolTurnDrivesPlanChangesAndTaskPanels",
		"TestAgentBackgroundShellToolJourneySettlesResources",
		"TestSaveConcurrentWritersLeaveCompleteTranscriptAndNoTemps",
		"TestCLISmokeVersionAndTheme",
		"TestProductionSmokeCommandsFailExplicitly",
		"Independent review blockers",
		"TestReleaseBinaryDoesNotExposeSmokeCommands",
		"TestSmokeTaggedBinaryBuilds",
		"TestPTYSmokeVersionCommand",
		"Test-only smoke isolation",
		"TestPTYSmokeAppShellKeyboardNavigation",
		"TestPTYAppShellNavigationSoak",
		"TestPTYReleaseAppShellLongerSoak",
		"TestPTYChatTUISmokeQuit",
		"CI enforcement",
		"TestGUIPhaseWorkflowRunsVerificationScript",
		"27859059893",
		"42c8a08f8b4752495f42e6a5aafc6aa0ae8c4077",
		"scripts/verify-gui-phase.sh",
		"go test ./... -count=1",
		"go test . ./docs ./internal/app ./internal/feed ./internal/gui ./internal/tui -count=1",
		"go test -tags 'wails production webkit2_41' ./internal/gui -count=1",
		"node --check internal/gui/static/app.js",
		"multi-surface desktop workspace",
		"node internal/gui/static/app_behavior_test.mjs",
		"scripts/gui-smoke.sh",
		"go test -tags smoke . -count=1",
		"go test ./docs ./internal/app ./internal/feed ./internal/gui ./internal/tui -shuffle=on -count=1",
		"go test -race ./internal/app ./internal/feed ./internal/tui -count=1",
		"go test . -run 'TestPTYReleaseAppShellLongerSoak' -count=1",
		"go test -tags smoke . -run",
		"-count=5",
		"docs/gui-current-surface-acceptance.md",
		"docs/gui-phase-gate.md",
		"docs/gui-delivery-notes.md",
		"docs/gui-next-phase-backlog.md",
		"Remaining gaps before claiming full persistent goal",
	} {
		if !strings.Contains(s, want) {
			t.Fatalf("GUI parity evidence missing %q", want)
		}
	}
}
